Initial commit
SVizor42/made_2019_cpp pull request #2
Opened 2019-11-07 18:53 UTC by SVizor42

2019-11-10 14:44 UTC, smirnov-vs requested changes

2019-11-10 14:44 UTC, smirnov-vs commented on 03/parser.cpp
> +    rtrim(input);
отступы поехали

2019-11-10 14:44 UTC, smirnov-vs commented on 03/main.cpp
> +	parser.Parse("Here is\nthe 2389 22	");
вроде как мувать строку внутрь не особо надо в общем случае, передача по значению тут будет больше мешать, чем помогать

2019-11-10 14:44 UTC, smirnov-vs commented on 03/parser.cpp
> +	beginFunction();
что если не задан колбэк?

2019-11-10 14:44 UTC, smirnov-vs commented on 03/parser.h
> +	void setEndFunc(onEndCallback func);
функторы в общем случае передавать по значению неоптимально

2019-11-10 14:44 UTC, smirnov-vs commented on 03/parser.cpp
> +		input.erase(0, pos + 1);
удаление неоптимально, достаточно чтения

2019-11-10 15:45 UTC, SVizor42 commented on 03/main.cpp
> +	parser.Parse("Here is\nthe 2389 22	");
Ок, поправил. Теперь передаю по ссылке.

2019-11-10 15:47 UTC, SVizor42 commented on 03/parser.cpp
> +	beginFunction();
Добавил проверку.

2019-11-10 15:47 UTC, SVizor42 commented on 03/parser.cpp
> +    rtrim(input);
Done.

2019-11-10 16:51 UTC, SVizor42 commented on 03/parser.h
> +	void setEndFunc(onEndCallback func);
Поправил, теперь по значению.

2019-11-10 16:58 UTC, SVizor42 commented on 03/parser.cpp
> +		input.erase(0, pos + 1);
Убрал erase.

2019-11-10 17:05 UTC, SVizor42 reviewed
Файлы отдельным коммитом.

2019-11-12 09:47 UTC, smirnov-vs approved these changes
привет!
я зачел

2019-11-12 09:47 UTC, smirnov-vs commented on 03/parser.cpp
> +	rtrim(input);
это архитектурно плохо - изменять чужие данные
всегда надо смотреть, можно ли сделать readonly

2019-11-12 10:48 UTC, merged