Initial commit for task-05
SVizor42/made_2019_cpp pull request #4
Opened 2019-11-19 20:48 UTC by SVizor42

2019-11-20 17:11 UTC, smirnov-vs requested changes

2019-11-20 17:11 UTC, smirnov-vs commented on main.cpp
> +            if (!isdigit)
хммм

2019-11-20 17:11 UTC, smirnov-vs commented on main.cpp
> +    Error operator()(ArgsT&... args) {
сериализатору ссылки незачем

2019-11-22 22:30 UTC, SVizor42 commented on main.cpp
> +    Error operator()(ArgsT&... args) {
Поправил.

2019-11-22 22:32 UTC, SVizor42 commented on main.cpp
> +            if (!isdigit)
Это рука-лицо, проглядел. И скомпилилось же.

2019-11-24 11:32 UTC, smirnov-vs approved these changes
привет!
я зачел

2019-11-24 11:32 UTC, smirnov-vs commented on main.cpp
> +    Error process(T& value, Args&... args) {
говорили, что ссылки не нужны

2019-11-29 11:36 UTC, SVizor42 commented on main.cpp
> +    Error process(T& value, Args&... args) {
Поправил.

2019-11-29 11:37 UTC, merged