Initial commit for task-07
SVizor42/made_2019_cpp pull request #6
Opened 2019-12-07 21:48 UTC by SVizor42

2019-12-09 08:51 UTC, smirnov-vs requested changes

2019-12-09 08:51 UTC, smirnov-vs commented on 07/format.h
> +			if (operation == 2) {
магические числа надо в enum

2019-12-09 08:51 UTC, smirnov-vs commented on 07/format.h
> +	}
возможно ли уменьшить ветвистость кода?

2019-12-09 10:57 UTC, SVizor42 commented on 07/format.h
> +			if (operation == 2) {
Перенес в enum.

2019-12-09 10:58 UTC, SVizor42 commented on 07/format.h
> +	}
Переписал через switch. Уровень вложений уменьшился, вроде как )

2019-12-11 19:49 UTC, smirnov-vs approved these changes
привет!
все окей

2019-12-11 20:51 UTC, merged