Initial commit for task-08
SVizor42/made_2019_cpp pull request #7
Opened 2019-12-11 12:29 UTC by SVizor42

2019-12-11 22:25 UTC, smirnov-vs requested changes

2019-12-11 22:25 UTC, smirnov-vs commented on 08/main.cpp
> +void print_vector(Vector<T>& v) {
изменять его не нужно

2019-12-11 22:25 UTC, smirnov-vs commented on 08/vector.h
> +		alloc_.construct(data_ + size_, std::forward<value_type>(value));
форвард rvalue

2019-12-12 07:31 UTC, SVizor42 commented on 08/main.cpp
> +void print_vector(Vector<T>& v) {
Поправил.

2019-12-12 07:31 UTC, SVizor42 commented on 08/vector.h
> +		alloc_.construct(data_ + size_, std::forward<value_type>(value));
Поправил.

2019-12-12 07:32 UTC, SVizor42 reviewed
Review fixies

2019-12-13 10:20 UTC, smirnov-vs approved these changes
привет!
все окей

2019-12-13 10:31 UTC, merged